### ISSUE TITLE
링크 404 오류

### ISSUE THREAD

**Issue by minjae9610** [chizcake/ReplayKitExample#1]
README.md의 Coder's High 링크에서 404 Error가 발생합니다.

**Comment by chizcake** [comment]
@minjae9610 님, 제보 감사합니다! 페이지의 주소가 변경되었네요. 
아래의 링크를 이용해주세요:
https://codershigh.github.io/WebSite/#/

`README.md` 파일은 곧 수정하겠습니다. 🙂
